### ISSUE TITLE
Bump http_parser dependency to version 0.6.1

### ISSUE THREAD

**Issue by fulldecent** [igrigorik/em-websocket#158]
Currently the latest version of em-websocket depends on version 0.6.0 of http_parser: 

> https://github.com/igrigorik/em-websocket/blob/v0.5.2/em-websocket.gemspec#L22

And that version has a nasty problem where you can't install it if the folder use are using has a space in it. It is fixed in version 0.6.1.

> https://github.com/tmm1/http_parser.rb/issues/65

Also, em-websocket is built in as a dependency for about half of statically-generated pages on the internet.

> https://github.com/github/pages-gem

---

So please bump the dependency.

**Comment by fulldecent** [comment]
I now see 0.6.1 has been yanked!

So really the solution here should be to require 0.7.0 or some later version.

**Comment by JamesVorder** [comment]
Landed here because I was trying to update the `http_parser` gem to the latest version on my system, and encountered the following error:

```
installing ruby-http_parser.rb (0.8.0-1) breaks dependency 'ruby-http_parser.rb<0.7' required by ruby-em-websocket
```

*Note:* I am managing my ruby gems with `yay`, a CLI interface to the arch user repository (aur).

The error above raises some questions for me:

1. Is there a reason that version 0.6.x is explicitly required by `em-websocket`?
2. How can I run the tests for this project, and are there contribution guidelines somewhere? I would like to try modifying the dependency locally, but don't want to step on any toes with a PR out of nowhere.

**Comment by JamesVorder** [comment]
Actually, I was able to run the tests successfully after updating the gemspec. Here is a bit of proof:

```
Finished in 2.76 seconds (files took 0.25498 seconds to load)
184 examples, 0 failures

em-websocket [master●] % bundle list
Gems included by the bundle:
[...]
  * em-websocket (0.5.2)
[...]
  * http_parser.rb (0.8.0)
[...]
```
So I think my woes and those of @fulldecent can be fixed with a one line change to the gemspec, requiring version 0.6.1 or above.

**Comment by fulldecent** [comment]
That change is a little dangerous because, assuming SemVer, anything could change between 0.6.1 and versions greater than 0.6.1. So providing an explicit range of known-good versions may be the best approach.

**Comment by JamesVorder** [comment]
I see what you mean, though it does look like the `eventmachine` dependency is specified in that way. Do you think it would be more appropriate just to express this dependency as ~> 0?

From the [Rubygems docs](https://guides.rubygems.org/patterns/#semantic-versioning):
```
Semantic versioning boils down to:

    PATCH 0.0.x level changes for implementation level detail changes, such as small bug fixes
    MINOR 0.x.0 level changes for any backwards compatible API changes, such as new functionality/features
    MAJOR x.0.0 level changes for backwards incompatible API changes, such as changes that will break existing users code if they update
```

**Comment by fulldecent** [comment]
I think we should use >= X && <= Y where we know that every version between X and Y inclusive work.

em-websocket is built into the stack for GitHub Pages and it powers many millions of websites. So this is the most conservative approach.

~> 0.6.1 is probably fine too. But we should check that all versions above 0.6.1 that are currently available today also work. Then if something new comes that breaks anything then it's THEIR fault not OURS :-)

**Comment by ClementGuillaudSaumur** [comment]
Hello, I faced the same issue (just starting few days ago), thanks @fulldecent for taking lead on the communication between projects regarding this old issue.

Since @JamesVorder ran the tests and you seems agree on how to manage the version of this dependency, the last thing is just to do it, right?

**Comment by igrigorik** [comment]
v0.5.3 should be live now, with a fix. thanks folks!

**Comment by fulldecent** [comment]
Awesome, thank you
